PortfolioSite/PortfolioSite/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioSite.Controllers
{
    [AllowAnonymous]
    public class AboutController : Controller
    {

        [HttpGet]
        public ActionResult About()
        {
            return View();
        }
    }
}

PortfolioSite/PortfolioSite/Controllers/HomeController.cs
using PortfolioSite.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioSite.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

PortfolioSite/PortfolioSite/Controllers/WorkController.cs
using PortfolioSite.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioSite.Controllers
{
    public class WorkController : Controller
    {
        // GET: Work
        public ActionResult Project(Project project)
        {
            return View(project.ToString());
        }
    }
}

PortfolioSite/PortfolioSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<main role="main-inner-wrapper" class="container">
    <div class="row">
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 ">
            <article role="pge-title-content">
                <header>
                    <h2><span>I DO</span> What I love doing</h2>
                </header>
                <p>I am very passionate about programming and spend a lot of my free time programming and carrying out research.  My predominant language is C# but I started programming using Java (I still use it from time to time).I am an extremely hard working, enthusiastic person and will put my all into whatever task I am given.</p>
            </article>
        </section>
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <article class="about-content">
                <p><span class="bold">Operating Systems:</span>                  Windows</p>
                <p><span class="bold">Strong Languages:</span> 	                C#, Java, MS SQL, MySql, Oracle, HTML & Javascript/JQuery, Delphi, CSS</p>
                <p><span class="bold">Frameworks:</span>                         MVC, WebAPI, ASP.NET, AngularJS, JQuery, Winforms, Ninject, ADO.NET/Entity Framework, Moq & NUnit</p>
                <p><span class="bold">Languages less experienced in:</span> 		C++, PHP,  R, Python, Solidarity</p>
                <p><span class="bold">Source Control:</span>                   	SVN (Tortoise SVN) & Git (via bash & Sourcetree/Git Extensions)</p>
                <p><span class="bold">Agile Management Software:</span> 	    	JIRA & Confluence</p>
                <p></p>
            </article>
        </section>
        <div class="clearfix"></div>
        <div class="thumbnails-pan">
            <section class="col-lg-12">
                <figure>
                    <img src="../images/about-images/me.jpg" class="img-responsive" />
                    <figcaption>
                        <h3>Matt Sharp</h3>
                        <h5>Developer</h5>
                    </figcaption>
                </figure>
            </section>
        </div>
    </div>
</main>

PortfolioSite/PortfolioSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main role="main-home-wrapper" class="container">
    <div class="row">
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 ">
            <article role="pge-title-content">
                <header role="work-title">
                    <h2><span>Matt Sharp</span>Portfolio</h2>
                    <a class="proj-url" href="https://github.com/msharp19/MyPortfolio">Git URL<i class="fa fa-external-link" aria-hidden="true"></i></a>
                </header>
            </article>
        </section>
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 grid">
            <figure class="effect-oscar">
                <div class="post-date url-exists url-red">
                    <i class="fa fa-lock lock-size"></i>
                    Private URL
                </div>
                <img src="~/images/work/wallet.jpg" alt="" class="img-responsive" />
                <figcaption class="text-center">
                    <h2 class="figure-item">ETH & MO<span> Wallet</span></h2>
                    <p>A wallet to manage funds between ETH and my ICO</p>
                    @Html.ActionLink("View More", "Project", "Work", new { project = "Wallet" }, new { @class = "work-item" })
                </figcaption>
            </figure>
        </section>
        <div class="clearfix"></div>
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 grid">
            <ul class="grid-lod effect-2" id="grid">
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/admin.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item"><span>Admin</span></h2>
                            <p>Provides a place to manage my chrome extension</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "MoAdmin" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/irc.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">IRC <span>Chat</span></h2>
                            <p>A secure way to chat on the web with messages only persisting on connection</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "IRC" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-green">
                            <i class="fa fa-check lock-size"></i>
                            Public URL
                        </div>
                        <img src="~/images/work/presale.png" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">ERC20 <span>Presale</span></h2>
                            <p>Presale launch site (test build)</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "Presale" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/browser.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Grab <span>Images</span></h2>
                            <p>Downloads images from cache on search engines</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "ImgGrab" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/crypto-bot.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Crypto<span> Bot</span></h2>
                            <p>Listens for change and alerts me via Telegram</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "CryptoBot" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-check lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/invoice.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Admin <span>Drinks</span></h2>
                            <p>I made my friend a drinks managment app</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "DrinksAdmin" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/web-job.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Web Jobs <span>Auto-Pay</span></h2>
                            <p>Cron Jobs on Azure</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "AutoPay" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
            </ul>
        </section>
        <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 grid">
            <ul class="grid-lod effect-2" id="grid">
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="../images/blog-main-images/network.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Modelling <span>CNN</span></h2>
                            <p>Trains a convolutional neural network to recognize images</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "CNNModeller" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-green">
                            <i class="fa fa-check lock-size"></i>
                            Public URL
                        </div>
                        <img src="~/images/work/request.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">View <span>Requests</span></h2>
                            <p>Reveals request details</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "RequestViewer" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/img.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Img Edit <span>CNN</span></h2>
                            <p>Create a function for cleaning image before training</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "ImgEdit" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/extension.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">Extension <span>Chrome</span></h2>
                            <p>Chrome extension overlay powered by WebAPI 2.0</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "ChromeExtension" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-red">
                            <i class="fa fa-lock lock-size"></i>
                            Private URL
                        </div>
                        <img src="~/images/work/video.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <div class="figure-text inline">
                                <h2 class="figure-item">Video<span> Chat</span></h2>
                                <p>Live feed via UDP</p>
                            </div>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "VideoChat" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <div class="post-date url-exists url-green">
                            <i class="fa fa-check lock-size"></i>
                            Public URL
                        </div>
                        <img src="~/images/work/contract.jpg" alt="" class="img-responsive" />
                        <figcaption class="text-center">
                            <h2 class="figure-item">MO<span> ICO</span></h2>
                            <p>An ERC20 Token</p>
                            @Html.ActionLink("View More", "Project", "Work", new { project = "ICO" }, new { @class = "work-item" })
                        </figcaption>
                    </figure>
                </li>
                <!--
                <li>
                    <figure class="effect-oscar">
                        <img src="~/images/home-images/image-3.jpg" alt="" class="img-responsive" />
                        <figcaption>]
                            <h2>Anatome Milano <span>Galleria</span></h2>
                            <p>Galerie Anatome based in Paris</p>
                            <a class="work-item" href="works-details.html">View more</a>
                        </figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="effect-oscar">
                        <img src="~/images/home-images/image-5.jpg" alt="" class="img-responsive" />
                        <figcaption>
                            <h2>A Brand <span>new Agency</span></h2>
                            <p>Over 40,000 customers use our themes to power their</p>
                            <a class="work-item" href="works-details.html">View more</a>
                        </figcaption>
                    </figure>
                </li>
                -->
            </ul>
        </section>
        <div class="clearfix"></div>
    </div>
</main>

@Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
@Scripts.Render("~/Scripts/home.js")
@Styles.Render("~/Content/style.css")